### ISSUE TITLE
Rainbow doesn't escape yaml specific symbols like : - &, etc.

### ISSUE THREAD

**Issue by stasmaxymov** [kamsar/Rainbow#11]
If you symbol to the field that is used for structuring yaml and then serialize item with a Rainbow. It come up with invalid yaml file that can't be parsed by 3-party parsers.
As example, start field with a '-' followed by space or end field with ':', the you will have in file:
**Value:  - some value**
I suggest to escape all values with doubleqoutes if they contain one of control symbols at least from Failsafe scheme:
-, :, [, ], {, }, !, ?

**Comment by kamsar** [comment]
This will be fixed in the next release. This may alter items as they are re-written to disk, but the format change is completely transparent to the Unicorn YAML parser (it can read with or without escaping in all cases). If you want to parse with other YAML parsers, you should reserialize after upgrading.

**Comment by kamsar** [comment]
Fixed in 3.1.4
